---

# file: playbooks/roles/db/defaults/main.yml

#
# MySQL
#
conf_mysql_flavour_debian_family: percona-xtradb-cluster
conf_mysql_version_debian_family: 5.6
conf_mysql_expire_logs_days: 3
conf_mysql_thread_stack: 576K
conf_mysql_key_buffer: 16M
conf_mysql_clustercheck_user: clustercheck
conf_mysql_clustercheck_password: clustercheck
conf_mysql_clustercheck_available_when_donor: 0
conf_mysql_innodb_log_file_size: 33554432
conf_mysql_ft_min_word_len: 3
conf_mysql_max_connections: 256
conf_mysql_max_allowed_packet: 256M
conf_mysql_query_cache_type: 1
conf_mysql_query_cache_limit: 1M
conf_mysql_query_cache_size: 8M
conf_mysql_innodb_buffer_pool_size: 64M
conf_mysql_thread_cache_size: 8
conf_mysql_table_cache: 32
conf_mysql_thread_concurrency: 3
conf_mysql_join_buffer_size: 256K
# conf_mysql_query_cache_limit: 1M
# conf_mysql_query_cache_size: 16M
conf_mysql_wait_timeout: 600
conf_mysql_lower_case_table_names: 1
conf_mysql_ft_boolean_syntax: ' |-><()~*:""&^'
conf_mysql_tmpdir: /run/mysqld
conf_mysql_report_host: atlantis
conf_mysql_replication: false
conf_mysql_replication_settings:
conf_mysql_server_id: 1
conf_galera_cluster: false

#
# galeranotify
#
conf_galera_notify_enable: false
conf_galera_notify_slack_enable: false

#
# Cassandra
#
conf_cassandra_enable: false
conf_cassandra_gpg_keyserver: pool.sks-keyservers.net
conf_cassandra_gpg_key_id: A278B781FE4B2BDA
conf_cassandra_series_version: 311x
conf_cassandra_cluster_name: "cassandra_cluster"
# conf_cassandra_listen_address: 127.0.0.1
# conf_cassandra_listen_interface: eth0
conf_cassandra_start_rpc: false
conf_cassandra_rpc_address: 0.0.0.0
conf_cassandra_broadcast_rpc_address: 127.0.0.1
conf_cassandra_rpc_port: 9160
conf_cassandra_endpoint_snitch: SimpleSnitch
conf_cassandra_rackdc_dc: dc1
conf_cassandra_rackdc_rack: rack1
conf_cassandra_topology: |
  # Cassandra Node IP=Data Center:Rack
  192.168.1.100=DC1:RAC1
  192.168.2.200=DC2:RAC2

  10.0.0.10=DC1:RAC1
  10.0.0.11=DC1:RAC1
  10.0.0.12=DC1:RAC2

  10.20.114.10=DC2:RAC1
  10.20.114.11=DC2:RAC1

  10.21.119.13=DC3:RAC1
  10.21.119.10=DC3:RAC1

  10.0.0.13=DC1:RAC2
  10.21.119.14=DC3:RAC2
  10.20.114.15=DC2:RAC2

  # default for unknown nodes
  default=DC1:r1

  # Native IPv6 is supported, however you must escape the colon in the IPv6 Address
  # Also be sure to comment out JVM_OPTS="$JVM_OPTS -Djava.net.preferIPv4Stack=true"
  # in cassandra-env.sh
  fe80\:0\:0\:0\:202\:b3ff\:fe1e\:8329=DC1:RAC3
