---

# file: playbooks/roles/common/handlers/main.yml

- name: handle_restart_rsyslog
  service: name=rsyslog state=restarted

- name: handle_update_locales
  command: dpkg-reconfigure --frontend noninteractive locales

- name: handle_restart_supervisor
  service: name=supervisord state=restarted
  when: conf_supervisor_started

- name: handle_restart_nullmailer
  service: name=nullmailer state=restarted

- name: handle_update_timezone
  command: dpkg-reconfigure --frontend noninteractive tzdata

- name: handle_restart_autofs
  service: name=autofs state=restarted

- name: handle_reload_docker
  service: name=docker state=reloaded

- name: handle_restart_docker
  service: name=docker state=restarted

- name: handle_restart_redis
  service: name={{ conf_redis_daemon }} state=restarted

- name: handle_restart_tinc
  service: name=tinc state=restarted

- name: handle_restart_vsftpd
  service: name=vsftpd state=restarted

- name: handle_restart_apache2
  service: name=apache2 state=restarted

- name: handle_restart_icinga2
  service: name=icinga2 state=restarted

- name: handle_reload_icinga2
  service: name=icinga2 state=reloaded

- name: handle_restart_zabbix_agent
  service: name="{{ conf_zabbix_agent_service }}" state=restarted

- name: handle_restart_munin
  service: name=munin state=restarted

- name: handle_restart_munin_node
  service: name=munin-node state=restarted

- name: handle_restart_carbon_cache
  service: name=carbon-cache state=restarted

- name: handle_restart_grafana
  service: name=grafana-server state=restarted

- name: handle_restart_fail2ban
  service: name=fail2ban state=restarted

- name: handle_restart_ssh
  service: name=ssh state=restarted

- name: handle_restart_autossh
  service: name=autossh state=restarted

- name: handle_restart_nfs
  service: name=nfs-kernel-server state=restarted

- name: handle_restart_telegraf
  service: name=telegraf state=restarted

- name: handle_assh_configbuild
  shell: /usr/local/go/bin/assh config build > ~/.ssh/config

- name: handle_start_rc_local
  service: name=rc.local state=started

- name: restart firewall
  service: name=firewall state=restarted

- name: handle_restart_netdata
  service: name=netdata state=restarted