---

# file: playbooks/roles/common/tasks/netdata.yml

- name: netdata apt-key (Ubuntu)
  apt_key:
    url: "https://packagecloud.io/netdata/netdata/gpgkey"
    state: present
  when: ansible_distribution == "Ubuntu"
  tags: [ netdata ]

- name: enable repo packagecloud.io/netdata/netdata (Ubuntu)
  apt_repository: repo='deb https://packagecloud.io/netdata/netdata/{{ ansible_distribution|lower }}/ {{ ansible_lsb.codename }} main' update_cache=yes
  when: ansible_distribution == "Ubuntu"
  tags: [ netdata ]

- name: install netdata (Debian family)
  package: name=netdata state=latest
  when: ansible_os_family == "Debian"
  tags: [ netdata ]

- name: netdata service state
  service: name=netdata state=started enabled=yes
  tags: [ netdata ]

- name: deploy /etc/netdata/netdata.conf
  template: src=etc/netdata/netdata.conf.j2 dest=/etc/netdata/netdata.conf owner=root group={{ conf_root_group }} mode=0644
  notify: handle_restart_netdata
  tags: [ netdata, netdata-conf ]

- name: deploy /etc/netdata/health_alarm_notify.conf
  template: src=etc/netdata/health_alarm_notify.conf.j2 dest=/etc/netdata/health_alarm_notify.conf owner=root group={{ conf_root_group }} mode=0644
  notify: handle_restart_netdata
  tags: [ netdata, netdata-conf ]